### ISSUE TITLE
hiDPI support?

### ISSUE THREAD

**Issue by GitSquared** [adi1090x/plymouth-themes#1]
Awesome work!
Could you render these at larger resolutions (like 1080p and 2160p 4K)?
Otherwise, could you give us any instructions on how to do so?
Cheers.

**Comment by adi1090x** [comment]
it should work on larger screens. have you tested these themes?

**Comment by GitSquared** [comment]
I did, they work but the image is smaller than it should be I think? Tested on 4K res.
Also it runs at a very slow framerate for some reason, that might just be the boot process kicking it off too fast though.

**Comment by adi1090x** [comment]
well, that just the image size. can't resize because it'll mess the quality. so i guess people have to deal with smaller images :sweat_smile:
