### ISSUE TITLE
"glow" conflicts with theme included in plymouth

### ISSUE THREAD

**Issue by real-or-random** [adi1090x/plymouth-themes#13]
See https://gitlab.freedesktop.org/plymouth/plymouth/-/tree/master/themes . This makes it impossible to install https://aur.archlinux.org/packages/plymouth-theme-glow-git/ due to filesystem conflicts. Maybe it should be renamed to `glow_alt`, I've seen that there is also `spinner_alt` (and `spinner` is a builtin theme too)

**Comment by tusqasi** [comment]
Keep which you want and move others to some other place. Then run the build command.

**Comment by real-or-random** [comment]
I know how to work around it. The point of the issue to encourage a fix that will not require a workaround.

**Comment by tusqasi** [comment]
Oh!

**Comment by adi1090x** [comment]
Resolved!

**Comment by real-or-random** [comment]
Thanks!
