### ISSUE TITLE
Bundle up with https://github.com/vinceliuice/grub2-themes ?

### ISSUE THREAD

**Issue by breversa** [adi1090x/plymouth-themes#16]
Hi there !

A few weeks apart, I randomly stumbled upon https://github.com/vinceliuice/grub2-themes and https://github.com/adi1090x/plymouth-themes

Playing with both of these projects, I noticed that some GRUB themes go very well with some Plymouth themes, for instance GRUB Tela with Plymouth Pixels. :-)

So I thought "Why not offer a bundle of presets, combining matching themes" ?

**Comment by breversa** [comment]
https://github.com/vinceliuice/grub2-themes/issues/104

**Comment by adi1090x** [comment]
Not yet planned. Besides, both are different projects.
