### ISSUE TITLE
/usr/lib64/plymouth/script.so Does not exist

### ISSUE THREAD

**Issue by reo6** [adi1090x/plymouth-themes#17]
```
✘  ~/D/p/pack_3   master ±  sudo plymouth-set-default-theme -l
apple-mac-plymouth
bgrt
darwin
details
fedoraspinning
pixels
spinner
text
tribar
 ~/D/p/pack_3   master ±  sudo plymouth-set-default-theme -R pixels
/usr/lib64/plymouth/script.so does not exist
```
You can see, there is pixels theme in directory. But, I can't set it.

I am using Fedora, Gnome on Wayland.

**Comment by rekybongso** [comment]
Try installing plymouth-plugin-script
Tested on my Fedora 33 machine

https://fedora.pkgs.org/33/fedora-x86_64/plymouth-plugin-script-0.9.4-16.20200325gite31c81f.fc33.x86_64.rpm.html

**Comment by hernankrama** [comment]
Me sirvió

**Comment by adi1090x** [comment]
Solved?

**Comment by reo6** [comment]
I don't remember, it's been 2 years. I currently couldn't reproduce the problem, so unless someone comes in with a new report, it can stay closed.

**Comment by Pingasmaster** [comment]
Not to revive an old thread but just to advise anyone stumbling across this issue, I had the same issue after trying to apply a plymouth screen with on Fedora 41 Workstation with Gnome 47, I fixed it with a simple 

```bash
dnf install plymouth-plugin-script
```

After that the first plymouth screen takes a long time to apply but let it do its thing and it will work.

**Comment by DedFishy** [comment]
On my Fedora machine, I had to copy the libraries from `/usr/lib64/plymouth` to `/usr/lib/plymouth` and copy `label-freetype.so` to `label.so` for it to apply the theme.
