### ISSUE TITLE
/usr/lib64/plymouth/script.so does not exist

### ISSUE THREAD

**Issue by ptrnull** [adi1090x/plymouth-themes#2]
When calling plymouth-set-default-theme to set the plymouth theme In FC31 it gives an error If the package plymouth-plugin-script is not installed.

```
$ sudo plymouth-set-default-theme -R abstract_ring
/usr/lib64/plymouth/script.so does not exist
```

A note should be included in the installing section advising about that case.

How to fix it:
`$ sudo dnf install plymouth-plugin-script -y`

**Comment by adi1090x** [comment]
done, thanks.
