### ISSUE TITLE
Unable to install new plymouth theme in Ubuntu, apart from the default ones

### ISSUE THREAD

**Issue by austinrojers** [adi1090x/plymouth-themes#27]
I tried to follow the following steps:

 ```
#make sure you have the packages for plymouth
sudo apt install plymouth

#after downloading or cloning themes, copy the selected theme in plymouth theme dir
sudo cp -r angular /usr/share/plymouth/themes/

#install the new theme (angular, in this case)
sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/angular/angular.plymouth 100

#select the theme to apply
sudo update-alternatives --config default.plymouth
(choose the number to the installed theme, angular in this case)

#update initramfs
sudo update-initramfs -u

```
It works with the preinstalled themes, But when I select a newly installed one, I just get my Dell logo until the login screen

Plymouth works during the reboot or shutdown process, but not on boot?

Could this be similar to this: https://forum.garudalinux.org/t/correct-plymouth-boot-theme-not-showing-up-on-boot/

If so, please tell me what the Ubuntu-specific steps are?

Thank you in advance

**Comment by austinrojers** [comment]
@adi1090x please have a look

**Comment by Tutul-** [comment]
it's probably because the default one tell Plymouth to drop the EFI framebuffer.
try to add  `fbcon=nodefer` to your kernel cmdline (when booting, press E when your are on the grub to edit your selected entry and add that to the end of the line starting by _linux_). It will tell the kernel to don't even keep that framebuffer so it will maybe let you see your theme

**Comment by austinrojers** [comment]
> it's probably because the default one tell Plymouth to drop the EFI framebuffer.
> try to add `fbcon=nodefer` to your kernel cmdline (when booting, press E when your are on the grub to edit your selected entry and add that to the end of the line starting by _linux_). It will tell the kernel to don't even keep that framebuffer so it will maybe let you see your theme

Thanks @Tutul, I no longer use Ubuntu or Ubuntu based distros.
I will check it out, if I use Ubuntu in the future.
