### ISSUE TITLE
Animation is not centered?

### ISSUE THREAD

**Issue by ftabaro** [adi1090x/plymouth-themes#3]
This package is great. Thank you for sharing your efforts! But I have a problem. Other Plymouth themes get nicely centered upon booting but the one I would like to use here (connect) does not. Any idea how to troubleshoot this?

**Comment by adi1090x** [comment]
do you face this issue with other themes in this repo?

**Comment by motorlatitude** [comment]
I would also like to thank you for your efforts! I had the issue that things were off-centre as well, I fixed it by adding the screen origin when aligning the animation. I think this is only an issue for multi-monitor setups. I went ahead and made a PR  #5 to fix it for all the animations and template to account for this.

**Comment by adi1090x** [comment]
i guess it's resolved. thanks @motorlatitude
