### ISSUE TITLE
Very nice, but they don't ask for LUKS password.

### ISSUE THREAD

**Issue by andrimanna** [adi1090x/plymouth-themes#4]
I've an encrypted boot volume and it doesn't ask me for the unlock password. I have to press esc every time.

**Comment by adi1090x** [comment]
i don't use encryption so I've tested on that.
I'll start working on this soon.

**Comment by eadwu** [comment]
It doesn't seem like `plymouth ask-for-password` doesn't work, it's more like the theme doesn't seem to work with any prompt at all weather `ask-for-password` for `message`.

**Comment by eadwu** [comment]
Yeah it's because the rest of the `Plymouth.Set*Function` are missing, copying them over from the default scripts allows `ask-for-password` and `message` to work. The image files needed are already present (the non `progress-N` images).

**Comment by adi1090x** [comment]
okay I've pushed some fixes, pls try and let me know if it works now.

**Comment by Zocker1999NET** [comment]
I tested the theme pack_2/glow today on a Debian Unstable system and my system showed me a prompt over the animation, maybe this is fixed now?

**Comment by adi1090x** [comment]
Great, now i just have to adjust the prompt position, thanks for feedback @Zocker1999NET

**Comment by nguyenhai97** [comment]
The password prompt make image look a bit off (it look like the height of the image smaller than screen size) on my machine, it work normal when I do reboot and when testing with showplymouth script. I'm using Archlinux and my screen resolution is 1366x768

**Comment by freundTech** [comment]
Thanks. This works now, but the design of the password prompt looks really out of place.
Maybe you could have a look at how this theme does the passwort prompt: https://github.com/nenad/arch-beat
I feel like that would fit way better with most (all?) of those themes.
